
# DO NOT EDIT THIS FILE

OBJS = $(addprefix $(OBJDIR), $(SOURCES:.cpp=.o))
DEPS = $(OBJS:.o=.d)

OUTDIR = ../../$(BUILD)/


ifeq ($(LINKER),$(AR))
	LFLAGS = $(ARFLAGS) $(LINKERFLAGS)
else ifeq ($(LINKER),$(LN))
	LFLAGS = $(LNFLAGS) $(LINKERFLAGS)
else ifeq ($(LINKER),$(EXE))
	LFLAGS = $(EXEFLAGS) $(LINKERFLAGS)
else
	$(error unknown linker)
endif


.PHONY: clean

objdir:
	@$(MKDIR) $(foreach SOURCE,$(SOURCES),$(OBJDIR)$(dir $(SOURCE)))

outdir:
	@$(MKDIR) $(OUTDIR)

$(OBJDIR)%.o: %.cpp
	$(CXX) $(CXXFLAGS) -MMD -c -o $@ $<

ifeq ($(LINKER),$(AR))
outputfile: objs
	$(LINKER) $(LFLAGS) $(OUTDIR)$(OUTNAME) $(OBJS)
else
outputfile: objs
	$(LINKER) $(OBJS) -o $(OUTDIR)$(OUTNAME) $(LFLAGS) -L$(OUTDIR) -Wl,-rpath-link,$(OUTDIR)
	$(MKDIR) ../../../game/linux
	$(CP) $(OUTDIR)$(OUTNAME) ../../../game/linux/$(OUTNAME)
endif

-include $(DEPS)

objs: objdir $(OBJS)

link: outdir outputfile

clean:
	rm -rf $(OBJS) $(DEPS) $(OUTDIR)$(OUTNAME)

